class BadgeSystem{constructor(){this.badges=this.initBadges();this.userBadges=this.loadUserBadges();}
initBadges(){return{streak_7:{id:"streak_7",name:"🔥 Semaine de feu",description:"7 jours consécutifs d'activité",category:"streak",xpBonus:100,condition:(userData)=>userData.currentStreak>=7,},streak_30:{id:"streak_30",name:"🏆 Champion du mois",description:"30 jours consécutifs d'activité",category:"streak",xpBonus:500,condition:(userData)=>userData.currentStreak>=30,},xp_1000:{id:"xp_1000",name:"📚 Érudit",description:"Atteindre 1000 XP au total",category:"xp",xpBonus:200,condition:(userData)=>userData.totalXP>=1000,},xp_5000:{id:"xp_5000",name:"🎓 Savant",description:"Atteindre 5000 XP au total",category:"xp",xpBonus:1000,condition:(userData)=>userData.totalXP>=5000,},perfect_10:{id:"perfect_10",name:"⭐ Sans faute",description:"Réussir 10 quiz avec 100%",category:"performance",xpBonus:150,condition:(userData)=>userData.perfectQuizCount>=10,},quiz_100:{id:"quiz_100",name:"💯 Centurion",description:"Compléter 100 quiz",category:"completion",xpBonus:300,condition:(userData)=>userData.totalQuizCompleted>=100,},all_subjects:{id:"all_subjects",name:"🌟 Polyvalent",description:"Au moins 1 quiz dans chaque matière",category:"polyvalence",xpBonus:250,condition:(userData)=>{const subjects=["francais","maths","anglais","sciences","histoire","geographie",];const quizBySubject=userData.quizBySubject||{};return subjects.every((s)=>(quizBySubject[s]||0)>0);},},jeune_ingenieur:{id:"jeune_ingenieur",name:"⚙️ Jeune ingénieur",description:"Réussir les 2 questions Technologie avancée en Sciences",category:"performance",xpBonus:200,condition:(userData)=>{const flag=localStorage.getItem("curieux_badge_ingenieur");return flag==="true";},},};}
loadUserBadges(){const official=localStorage.getItem("lemondedescurieux_badges");if(official){try{const badges=JSON.parse(official);return{earned:badges.filter((b)=>b.unlocked).map((b)=>b.id),earnedDates:badges.reduce((acc,b)=>{if(b.unlocked&&b.unlockedAt)
acc[b.id]=new Date(b.unlockedAt).getTime();return acc;},{}),notifications:[],};}catch(e){console.error("[BadgeSystem] Erreur parsing badges officiels:",e);}}
const saved=localStorage.getItem("userBadges");if(saved){return JSON.parse(saved);}
return{earned:[],earnedDates:{},notifications:[],};}
saveUserBadges(){const dashboardFormat=Object.keys(this.badges).map((badgeId)=>{const isUnlocked=this.userBadges.earned.includes(badgeId);return{id:badgeId,unlocked:isUnlocked,unlockedAt:isUnlocked?new Date(this.userBadges.earnedDates[badgeId]||Date.now(),).toISOString():null,};});localStorage.setItem("lemondedescurieux_badges",JSON.stringify(dashboardFormat),);localStorage.setItem("userBadges",JSON.stringify(this.userBadges));console.log("✅ Badges sauvegardés:",dashboardFormat.filter((b)=>b.unlocked).length,"badges débloqués",);}
getUserData(){let userData={totalXP:0,currentStreak:0,perfectQuizCount:0,totalQuizCompleted:0,quizBySubject:{francais:0,maths:0,anglais:0,sciences:0,histoire:0,geographie:0,},};const officialXP=localStorage.getItem("lemondedescurieux_xp");if(officialXP){try{const xp=JSON.parse(officialXP);const bySection=xp.bySection||{};userData.totalXP=(bySection.francais||0)+
(bySection.anglais||0)+
(bySection.maths||0)+
(bySection.sciences||0)+
(bySection.histoire||0)+
(bySection.badges||0);console.log("[BadgeSystem] Total XP recalculé:",userData.totalXP,"depuis sections:",bySection,);}catch(e){console.error("[BadgeSystem] Erreur parsing XP:",e);}}
if(userData.totalXP===0){const oldXP=localStorage.getItem("section-xp-data");if(oldXP){try{const xp=JSON.parse(oldXP);userData.totalXP=Object.values(xp).reduce((sum,val)=>(typeof val==="number"?sum+val:sum),0,);}catch(e){}}}
const officialStreak=localStorage.getItem("lemondedescurieux_streaks");if(officialStreak){try{const streak=JSON.parse(officialStreak);userData.currentStreak=streak.currentStreak||0;}catch(e){}}
if(userData.currentStreak===0){const oldStreak=localStorage.getItem("dailyStreak");if(oldStreak){try{const streak=JSON.parse(oldStreak);userData.currentStreak=streak.currentStreak||0;}catch(e){}}}
const quizStats=localStorage.getItem("lemondedescurieux_quiz_stats");if(quizStats){try{const stats=JSON.parse(quizStats);userData.totalQuizCompleted=stats.totalCompleted||0;userData.perfectQuizCount=stats.perfectCount||0;if(stats.bySubject){Object.keys(userData.quizBySubject).forEach((s)=>{userData.quizBySubject[s]=stats.bySubject[s]||0;});}}catch(e){}}
if(userData.totalQuizCompleted===0){const progressData=localStorage.getItem("progressData");if(progressData){try{const progress=JSON.parse(progressData);Object.keys(progress).forEach((section)=>{const sectionData=progress[section];if(sectionData.quizResults){Object.values(sectionData.quizResults).forEach((result)=>{userData.totalQuizCompleted++;if(result.score===100||result.correctAnswers===result.totalQuestions){userData.perfectQuizCount++;}
const subjectKey=section.toLowerCase();if(userData.quizBySubject.hasOwnProperty(subjectKey)){userData.quizBySubject[subjectKey]++;}});}});}catch(e){}}}
return userData;}
checkBadges(){const userData=this.getUserData();const newBadges=[];Object.keys(this.badges).forEach((badgeId)=>{const badge=this.badges[badgeId];if(this.userBadges.earned.includes(badgeId)){return;}
if(badge.condition(userData)){this.unlockBadge(badgeId);newBadges.push(badge);}});return newBadges;}
unlockBadge(badgeId){if(this.userBadges.earned.includes(badgeId)){return;}
const badge=this.badges[badgeId];const now=Date.now();this.userBadges.earned.push(badgeId);this.userBadges.earnedDates[badgeId]=now;this.userBadges.notifications.push(badgeId);this.saveUserBadges();if(badge.xpBonus>0){this.addBadgeXP(badgeId,badge.xpBonus);}
console.log(`🎉 Badge débloqué: ${badge.name}`);}
addBadgeXP(badgeId,xpAmount){try{const raw=localStorage.getItem("lemondedescurieux_xp");let xp=raw?JSON.parse(raw):{total:0,bySection:{}};if(!xp.bySection)xp.bySection={};xp.bySection.badges=(xp.bySection.badges||0)+xpAmount;xp.total=(xp.total||0)+xpAmount;localStorage.setItem("lemondedescurieux_xp",JSON.stringify(xp));console.log(`✨ +${xpAmount} XP bonus badge ${badgeId} → total: ${xp.total}`,);}catch(e){console.warn("[BadgeSystem] Erreur addBadgeXP:",e);}}
getEarnedBadges(){return this.userBadges.earned.map((id)=>({...this.badges[id],earnedDate:this.userBadges.earnedDates[id],}));}
getUnlockedBadges(){const userData=this.getUserData();return Object.keys(this.badges).filter((id)=>!this.userBadges.earned.includes(id)).map((id)=>{const badge=this.badges[id];return{...badge,progress:this.calculateProgress(badge,userData),};});}
calculateProgress(badge,userData){switch(badge.id){case"streak_7":return{current:userData.currentStreak,target:7};case"streak_30":return{current:userData.currentStreak,target:30};case"xp_1000":return{current:userData.totalXP,target:1000};case"xp_5000":return{current:userData.totalXP,target:5000};case"perfect_10":return{current:userData.perfectQuizCount,target:10};case"quiz_100":return{current:userData.totalQuizCompleted,target:100};case"all_subjects":{const completed=Object.values(userData.quizBySubject).filter((v)=>v>0,).length;return{current:completed,target:6};}
case"jeune_ingenieur":{const flag=localStorage.getItem("curieux_badge_ingenieur");return{current:flag==="true"?1:0,target:1};}
default:return{current:0,target:1};}}
getPendingNotifications(){return this.userBadges.notifications.map((id)=>this.badges[id]);}
clearNotifications(){this.userBadges.notifications=[];this.saveUserBadges();}
getStats(){const total=Object.keys(this.badges).length;const earned=this.userBadges.earned.length;const totalXPBonus=this.getEarnedBadges().reduce((sum,badge)=>sum+badge.xpBonus,0,);return{total,earned,remaining:total-earned,completionRate:Math.round((earned/total)*100),totalXPBonus,};}
reset(){this.userBadges={earned:[],earnedDates:{},notifications:[],};this.saveUserBadges();console.log("🔄 Badges réinitialisés");}}
window.BadgeSystem=BadgeSystem;window.badgeSystem=new BadgeSystem();console.log("✅ Badge System chargé");