const BRIDGE={KEYS:{XP:'lemondedescurieux_xp',STREAKS:'lemondedescurieux_streaks',HEARTS:'lemondedescurieux_hearts',BADGES:'lemondedescurieux_badges'},_read(key){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null;}catch(e){console.warn('[BRIDGE] Erreur lecture clé:',key,e);return null;}},_write(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch(e){console.warn('[BRIDGE] Erreur écriture clé:',key,e);}},syncXP(){let xp=this._read(this.KEYS.XP)||{total:0,bySection:{}};const curioXP=this._read('curio_xp');if(typeof curioXP==='number'&&curioXP>xp.total){xp.total=curioXP;console.log('[BRIDGE] curio_xp fusionné:',curioXP);}
const sectionData=this._read('section-xp-data');if(sectionData&&typeof sectionData==='object'){for(const[section,val]of Object.entries(sectionData)){const current=xp.bySection[section]||0;if(typeof val==='number'&&val>current){xp.bySection[section]=val;}}
const sumSections=Object.values(xp.bySection).reduce((a,b)=>a+b,0);if(sumSections>xp.total){xp.total=sumSections;}
console.log('[BRIDGE] section-xp-data fusionné');}
const demo=this._read('demo_userData_v2');if(demo){if(demo.xp>xp.total){xp.total=demo.xp;}
console.log('[BRIDGE] demo_userData_v2 XP fusionné:',demo.xp);}
this._write(this.KEYS.XP,xp);return xp;},syncStreaks(){let streaks=this._read(this.KEYS.STREAKS)||{currentStreak:0,lastDate:null};const demo=this._read('demo_userData_v2');if(demo&&demo.streak>streaks.currentStreak){streaks.currentStreak=demo.streak;console.log('[BRIDGE] Streak fusionné depuis démo:',demo.streak);}
this._write(this.KEYS.STREAKS,streaks);return streaks;},syncHearts(){let hearts=this._read(this.KEYS.HEARTS)||{bySection:{}};const demo=this._read('demo_userData_v2');if(demo&&typeof demo.hearts==='number'){hearts.bySection.global={current:demo.hearts,max:demo.maxHearts||5};console.log('[BRIDGE] Hearts fusionné depuis démo:',demo.hearts);}
const oldHearts=this._read('hearts');if(oldHearts&&typeof oldHearts==='object'){for(const[section,val]of Object.entries(oldHearts)){if(!hearts.bySection[section]&&val){hearts.bySection[section]=val;}}}
this._write(this.KEYS.HEARTS,hearts);return hearts;},syncBadges(){let badges=this._read(this.KEYS.BADGES)||[];const userBadges=this._read('userBadges');if(userBadges&&userBadges.earned&&Array.isArray(userBadges.earned)){for(const badgeId of userBadges.earned){if(!badges.find(b=>b.id===badgeId)){badges.push({id:badgeId,unlocked:true,unlockedAt:(userBadges.earnedDates&&userBadges.earnedDates[badgeId])||Date.now()});}}}else if(Array.isArray(userBadges)){for(const badge of userBadges){if(badge.unlocked&&!badges.find(b=>b.id===badge.id)){badges.push({id:badge.id,unlocked:true,unlockedAt:badge.unlockedAt||Date.now()});}}}else if(userBadges&&typeof userBadges==='object'){for(const[id,data]of Object.entries(userBadges)){if(data&&data.unlocked&&!badges.find(b=>b.id===id)){badges.push({id,unlocked:true,unlockedAt:data.unlockedAt||Date.now()});}}}
const demo=this._read('demo_userData_v2');if(demo&&Array.isArray(demo.badges)){for(const badgeId of demo.badges){if(!badges.find(b=>b.id===badgeId)){badges.push({id:badgeId,unlocked:true,unlockedAt:Date.now()});}}}
this._write(this.KEYS.BADGES,badges);return badges;},syncAll(){console.log('[BRIDGE] Synchronisation démarrage...');const xp=this.syncXP();const streaks=this.syncStreaks();const hearts=this.syncHearts();const badges=this.syncBadges();console.log('[BRIDGE] ✅ Sync complet →',{xp,streaks,hearts,badges});return{xp,streaks,hearts,badges};}};window.BRIDGE=BRIDGE;document.addEventListener('DOMContentLoaded',()=>{BRIDGE.syncAll();});